gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT lemon.o -MD -MP -MF .deps/lemon.Tpo -c -o lemon.o lemon.c
mv -f .deps/lemon.Tpo .deps/lemon.Po
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fPIC  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99   -o lemon lemon.o  
#libtool: link: gcc -fPIC -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -o lemon lemon.o 
rm -f configparser.h
../src/lemon -q ./configparser.y ./lempar.c
rm -f mod_ssi_exprparser.h
../src/lemon -q ./mod_ssi_exprparser.y ./lempar.c
cd /home/gx/Documents/Git/osv/apps/lighttpd/upstream/lighttpd-1.4.35/src
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_flv_streaming.lo -MD -MP -MF .deps/mod_flv_streaming.Tpo -c -o mod_flv_streaming.lo mod_flv_streaming.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_flv_streaming.lo -MD -MP -MF .deps/mod_flv_streaming.Tpo -c mod_flv_streaming.c  -fPIC -DPIC -o .libs/mod_flv_streaming.o
mv -f .deps/mod_flv_streaming.Tpo .deps/mod_flv_streaming.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fPIC  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -module -export-dynamic -avoid-version  -o mod_flv_streaming.la -rpath /usr/local/lib mod_flv_streaming.lo  
#libtool: link: gcc -fPIC -shared  -fPIC -DPIC  .libs/mod_flv_streaming.o    -O2   -Wl,-soname -Wl,mod_flv_streaming.so -o .libs/mod_flv_streaming.so
cd ".libs" && rm -f "mod_flv_streaming.la" && ln -s "../mod_flv_streaming.la" "mod_flv_streaming.la" && cd ..
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_evasive.lo -MD -MP -MF .deps/mod_evasive.Tpo -c -o mod_evasive.lo mod_evasive.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_evasive.lo -MD -MP -MF .deps/mod_evasive.Tpo -c mod_evasive.c  -fPIC -DPIC -o .libs/mod_evasive.o
mv -f .deps/mod_evasive.Tpo .deps/mod_evasive.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fPIC  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -module -export-dynamic -avoid-version  -o mod_evasive.la -rpath /usr/local/lib mod_evasive.lo  
#libtool: link: gcc -fPIC -shared  -fPIC -DPIC  .libs/mod_evasive.o    -O2   -Wl,-soname -Wl,mod_evasive.so -o .libs/mod_evasive.so
cd ".libs" && rm -f "mod_evasive.la" && ln -s "../mod_evasive.la" "mod_evasive.la" && cd ..
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES     -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_webdav_la-mod_webdav.lo -MD -MP -MF .deps/mod_webdav_la-mod_webdav.Tpo -c -o mod_webdav_la-mod_webdav.lo `test -f 'mod_webdav.c' || echo './'`mod_webdav.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_webdav_la-mod_webdav.lo -MD -MP -MF .deps/mod_webdav_la-mod_webdav.Tpo -c mod_webdav.c  -fPIC -DPIC -o .libs/mod_webdav_la-mod_webdav.o
mv -f .deps/mod_webdav_la-mod_webdav.Tpo .deps/mod_webdav_la-mod_webdav.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fPIC     -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -module -export-dynamic -avoid-version  -o mod_webdav.la -rpath /usr/local/lib mod_webdav_la-mod_webdav.lo     
#libtool: link: gcc -fPIC -shared  -fPIC -DPIC  .libs/mod_webdav_la-mod_webdav.o    -O2   -Wl,-soname -Wl,mod_webdav.so -o .libs/mod_webdav.so
cd ".libs" && rm -f "mod_webdav.la" && ln -s "../mod_webdav.la" "mod_webdav.la" && cd ..
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES   -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_magnet_la-mod_magnet.lo -MD -MP -MF .deps/mod_magnet_la-mod_magnet.Tpo -c -o mod_magnet_la-mod_magnet.lo `test -f 'mod_magnet.c' || echo './'`mod_magnet.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_magnet_la-mod_magnet.lo -MD -MP -MF .deps/mod_magnet_la-mod_magnet.Tpo -c mod_magnet.c  -fPIC -DPIC -o .libs/mod_magnet_la-mod_magnet.o
mv -f .deps/mod_magnet_la-mod_magnet.Tpo .deps/mod_magnet_la-mod_magnet.Plo
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES   -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_magnet_la-mod_magnet_cache.lo -MD -MP -MF .deps/mod_magnet_la-mod_magnet_cache.Tpo -c -o mod_magnet_la-mod_magnet_cache.lo `test -f 'mod_magnet_cache.c' || echo './'`mod_magnet_cache.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_magnet_la-mod_magnet_cache.lo -MD -MP -MF .deps/mod_magnet_la-mod_magnet_cache.Tpo -c mod_magnet_cache.c  -fPIC -DPIC -o .libs/mod_magnet_la-mod_magnet_cache.o
mv -f .deps/mod_magnet_la-mod_magnet_cache.Tpo .deps/mod_magnet_la-mod_magnet_cache.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fPIC   -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -module -export-dynamic -avoid-version  -o mod_magnet.la -rpath /usr/local/lib mod_magnet_la-mod_magnet.lo mod_magnet_la-mod_magnet_cache.lo   -lm 
#libtool: link: gcc -fPIC -shared  -fPIC -DPIC  .libs/mod_magnet_la-mod_magnet.o .libs/mod_magnet_la-mod_magnet_cache.o   -lm  -O2   -Wl,-soname -Wl,mod_magnet.so -o .libs/mod_magnet.so
cd ".libs" && rm -f "mod_magnet.la" && ln -s "../mod_magnet.la" "mod_magnet.la" && cd ..
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES   -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_cml_la-mod_cml.lo -MD -MP -MF .deps/mod_cml_la-mod_cml.Tpo -c -o mod_cml_la-mod_cml.lo `test -f 'mod_cml.c' || echo './'`mod_cml.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_cml_la-mod_cml.lo -MD -MP -MF .deps/mod_cml_la-mod_cml.Tpo -c mod_cml.c  -fPIC -DPIC -o .libs/mod_cml_la-mod_cml.o
mv -f .deps/mod_cml_la-mod_cml.Tpo .deps/mod_cml_la-mod_cml.Plo
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES   -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_cml_la-mod_cml_lua.lo -MD -MP -MF .deps/mod_cml_la-mod_cml_lua.Tpo -c -o mod_cml_la-mod_cml_lua.lo `test -f 'mod_cml_lua.c' || echo './'`mod_cml_lua.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_cml_la-mod_cml_lua.lo -MD -MP -MF .deps/mod_cml_la-mod_cml_lua.Tpo -c mod_cml_lua.c  -fPIC -DPIC -o .libs/mod_cml_la-mod_cml_lua.o
mv -f .deps/mod_cml_la-mod_cml_lua.Tpo .deps/mod_cml_la-mod_cml_lua.Plo
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES   -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_cml_la-mod_cml_funcs.lo -MD -MP -MF .deps/mod_cml_la-mod_cml_funcs.Tpo -c -o mod_cml_la-mod_cml_funcs.lo `test -f 'mod_cml_funcs.c' || echo './'`mod_cml_funcs.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_cml_la-mod_cml_funcs.lo -MD -MP -MF .deps/mod_cml_la-mod_cml_funcs.Tpo -c mod_cml_funcs.c  -fPIC -DPIC -o .libs/mod_cml_la-mod_cml_funcs.o
mv -f .deps/mod_cml_la-mod_cml_funcs.Tpo .deps/mod_cml_la-mod_cml_funcs.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fPIC   -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -module -export-dynamic -avoid-version  -o mod_cml.la -rpath /usr/local/lib mod_cml_la-mod_cml.lo mod_cml_la-mod_cml_lua.lo mod_cml_la-mod_cml_funcs.lo    -lm 
#libtool: link: gcc -fPIC -shared  -fPIC -DPIC  .libs/mod_cml_la-mod_cml.o .libs/mod_cml_la-mod_cml_lua.o .libs/mod_cml_la-mod_cml_funcs.o   -lm  -O2   -Wl,-soname -Wl,mod_cml.so -o .libs/mod_cml.so
cd ".libs" && rm -f "mod_cml.la" && ln -s "../mod_cml.la" "mod_cml.la" && cd ..
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_trigger_b4_dl.lo -MD -MP -MF .deps/mod_trigger_b4_dl.Tpo -c -o mod_trigger_b4_dl.lo mod_trigger_b4_dl.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_trigger_b4_dl.lo -MD -MP -MF .deps/mod_trigger_b4_dl.Tpo -c mod_trigger_b4_dl.c  -fPIC -DPIC -o .libs/mod_trigger_b4_dl.o
mv -f .deps/mod_trigger_b4_dl.Tpo .deps/mod_trigger_b4_dl.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fPIC  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -module -export-dynamic -avoid-version  -o mod_trigger_b4_dl.la -rpath /usr/local/lib mod_trigger_b4_dl.lo   -lpcre  
#libtool: link: gcc -fPIC -shared  -fPIC -DPIC  .libs/mod_trigger_b4_dl.o   -lpcre  -O2   -Wl,-soname -Wl,mod_trigger_b4_dl.so -o .libs/mod_trigger_b4_dl.so
cd ".libs" && rm -f "mod_trigger_b4_dl.la" && ln -s "../mod_trigger_b4_dl.la" "mod_trigger_b4_dl.la" && cd ..
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_mysql_vhost_la-mod_mysql_vhost.lo -MD -MP -MF .deps/mod_mysql_vhost_la-mod_mysql_vhost.Tpo -c -o mod_mysql_vhost_la-mod_mysql_vhost.lo `test -f 'mod_mysql_vhost.c' || echo './'`mod_mysql_vhost.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_mysql_vhost_la-mod_mysql_vhost.lo -MD -MP -MF .deps/mod_mysql_vhost_la-mod_mysql_vhost.Tpo -c mod_mysql_vhost.c  -fPIC -DPIC -o .libs/mod_mysql_vhost_la-mod_mysql_vhost.o
mv -f .deps/mod_mysql_vhost_la-mod_mysql_vhost.Tpo .deps/mod_mysql_vhost_la-mod_mysql_vhost.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fPIC  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -module -export-dynamic -avoid-version  -o mod_mysql_vhost.la -rpath /usr/local/lib mod_mysql_vhost_la-mod_mysql_vhost.lo   
#libtool: link: gcc -fPIC -shared  -fPIC -DPIC  .libs/mod_mysql_vhost_la-mod_mysql_vhost.o    -O2   -Wl,-soname -Wl,mod_mysql_vhost.so -o .libs/mod_mysql_vhost.so
cd ".libs" && rm -f "mod_mysql_vhost.la" && ln -s "../mod_mysql_vhost.la" "mod_mysql_vhost.la" && cd ..
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_cgi.lo -MD -MP -MF .deps/mod_cgi.Tpo -c -o mod_cgi.lo mod_cgi.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_cgi.lo -MD -MP -MF .deps/mod_cgi.Tpo -c mod_cgi.c  -fPIC -DPIC -o .libs/mod_cgi.o
mv -f .deps/mod_cgi.Tpo .deps/mod_cgi.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fPIC  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -module -export-dynamic -avoid-version  -o mod_cgi.la -rpath /usr/local/lib mod_cgi.lo  
#libtool: link: gcc -fPIC -shared  -fPIC -DPIC  .libs/mod_cgi.o    -O2   -Wl,-soname -Wl,mod_cgi.so -o .libs/mod_cgi.so
cd ".libs" && rm -f "mod_cgi.la" && ln -s "../mod_cgi.la" "mod_cgi.la" && cd ..
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_scgi.lo -MD -MP -MF .deps/mod_scgi.Tpo -c -o mod_scgi.lo mod_scgi.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_scgi.lo -MD -MP -MF .deps/mod_scgi.Tpo -c mod_scgi.c  -fPIC -DPIC -o .libs/mod_scgi.o
mv -f .deps/mod_scgi.Tpo .deps/mod_scgi.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fPIC  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -module -export-dynamic -avoid-version  -o mod_scgi.la -rpath /usr/local/lib mod_scgi.lo  
#libtool: link: gcc -fPIC -shared  -fPIC -DPIC  .libs/mod_scgi.o    -O2   -Wl,-soname -Wl,mod_scgi.so -o .libs/mod_scgi.so
cd ".libs" && rm -f "mod_scgi.la" && ln -s "../mod_scgi.la" "mod_scgi.la" && cd ..
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_staticfile.lo -MD -MP -MF .deps/mod_staticfile.Tpo -c -o mod_staticfile.lo mod_staticfile.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_staticfile.lo -MD -MP -MF .deps/mod_staticfile.Tpo -c mod_staticfile.c  -fPIC -DPIC -o .libs/mod_staticfile.o
mv -f .deps/mod_staticfile.Tpo .deps/mod_staticfile.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fPIC  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -module -export-dynamic -avoid-version  -o mod_staticfile.la -rpath /usr/local/lib mod_staticfile.lo  
#libtool: link: gcc -fPIC -shared  -fPIC -DPIC  .libs/mod_staticfile.o    -O2   -Wl,-soname -Wl,mod_staticfile.so -o .libs/mod_staticfile.so
cd ".libs" && rm -f "mod_staticfile.la" && ln -s "../mod_staticfile.la" "mod_staticfile.la" && cd ..
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_dirlisting.lo -MD -MP -MF .deps/mod_dirlisting.Tpo -c -o mod_dirlisting.lo mod_dirlisting.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_dirlisting.lo -MD -MP -MF .deps/mod_dirlisting.Tpo -c mod_dirlisting.c  -fPIC -DPIC -o .libs/mod_dirlisting.o
mv -f .deps/mod_dirlisting.Tpo .deps/mod_dirlisting.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fPIC  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -module -export-dynamic -avoid-version  -o mod_dirlisting.la -rpath /usr/local/lib mod_dirlisting.lo  -lpcre 
#libtool: link: gcc -fPIC -shared  -fPIC -DPIC  .libs/mod_dirlisting.o   -lpcre  -O2   -Wl,-soname -Wl,mod_dirlisting.so -o .libs/mod_dirlisting.so
cd ".libs" && rm -f "mod_dirlisting.la" && ln -s "../mod_dirlisting.la" "mod_dirlisting.la" && cd ..
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_indexfile.lo -MD -MP -MF .deps/mod_indexfile.Tpo -c -o mod_indexfile.lo mod_indexfile.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_indexfile.lo -MD -MP -MF .deps/mod_indexfile.Tpo -c mod_indexfile.c  -fPIC -DPIC -o .libs/mod_indexfile.o
mv -f .deps/mod_indexfile.Tpo .deps/mod_indexfile.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fPIC  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -module -export-dynamic -avoid-version  -o mod_indexfile.la -rpath /usr/local/lib mod_indexfile.lo  
#libtool: link: gcc -fPIC -shared  -fPIC -DPIC  .libs/mod_indexfile.o    -O2   -Wl,-soname -Wl,mod_indexfile.so -o .libs/mod_indexfile.so
cd ".libs" && rm -f "mod_indexfile.la" && ln -s "../mod_indexfile.la" "mod_indexfile.la" && cd ..
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_setenv.lo -MD -MP -MF .deps/mod_setenv.Tpo -c -o mod_setenv.lo mod_setenv.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_setenv.lo -MD -MP -MF .deps/mod_setenv.Tpo -c mod_setenv.c  -fPIC -DPIC -o .libs/mod_setenv.o
mv -f .deps/mod_setenv.Tpo .deps/mod_setenv.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fPIC  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -module -export-dynamic -avoid-version  -o mod_setenv.la -rpath /usr/local/lib mod_setenv.lo  
#libtool: link: gcc -fPIC -shared  -fPIC -DPIC  .libs/mod_setenv.o    -O2   -Wl,-soname -Wl,mod_setenv.so -o .libs/mod_setenv.so
cd ".libs" && rm -f "mod_setenv.la" && ln -s "../mod_setenv.la" "mod_setenv.la" && cd ..
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_alias.lo -MD -MP -MF .deps/mod_alias.Tpo -c -o mod_alias.lo mod_alias.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_alias.lo -MD -MP -MF .deps/mod_alias.Tpo -c mod_alias.c  -fPIC -DPIC -o .libs/mod_alias.o
mv -f .deps/mod_alias.Tpo .deps/mod_alias.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fPIC  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -module -export-dynamic -avoid-version  -o mod_alias.la -rpath /usr/local/lib mod_alias.lo  
#libtool: link: gcc -fPIC -shared  -fPIC -DPIC  .libs/mod_alias.o    -O2   -Wl,-soname -Wl,mod_alias.so -o .libs/mod_alias.so
cd ".libs" && rm -f "mod_alias.la" && ln -s "../mod_alias.la" "mod_alias.la" && cd ..
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_userdir.lo -MD -MP -MF .deps/mod_userdir.Tpo -c -o mod_userdir.lo mod_userdir.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_userdir.lo -MD -MP -MF .deps/mod_userdir.Tpo -c mod_userdir.c  -fPIC -DPIC -o .libs/mod_userdir.o
mv -f .deps/mod_userdir.Tpo .deps/mod_userdir.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fPIC  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -module -export-dynamic -avoid-version  -o mod_userdir.la -rpath /usr/local/lib mod_userdir.lo  
#libtool: link: gcc -fPIC -shared  -fPIC -DPIC  .libs/mod_userdir.o    -O2   -Wl,-soname -Wl,mod_userdir.so -o .libs/mod_userdir.so
cd ".libs" && rm -f "mod_userdir.la" && ln -s "../mod_userdir.la" "mod_userdir.la" && cd ..
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_rrdtool.lo -MD -MP -MF .deps/mod_rrdtool.Tpo -c -o mod_rrdtool.lo mod_rrdtool.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_rrdtool.lo -MD -MP -MF .deps/mod_rrdtool.Tpo -c mod_rrdtool.c  -fPIC -DPIC -o .libs/mod_rrdtool.o
mv -f .deps/mod_rrdtool.Tpo .deps/mod_rrdtool.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fPIC  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -module -export-dynamic -avoid-version  -o mod_rrdtool.la -rpath /usr/local/lib mod_rrdtool.lo  
#libtool: link: gcc -fPIC -shared  -fPIC -DPIC  .libs/mod_rrdtool.o    -O2   -Wl,-soname -Wl,mod_rrdtool.so -o .libs/mod_rrdtool.so
cd ".libs" && rm -f "mod_rrdtool.la" && ln -s "../mod_rrdtool.la" "mod_rrdtool.la" && cd ..
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_usertrack.lo -MD -MP -MF .deps/mod_usertrack.Tpo -c -o mod_usertrack.lo mod_usertrack.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_usertrack.lo -MD -MP -MF .deps/mod_usertrack.Tpo -c mod_usertrack.c  -fPIC -DPIC -o .libs/mod_usertrack.o
mv -f .deps/mod_usertrack.Tpo .deps/mod_usertrack.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fPIC  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -module -export-dynamic -avoid-version  -o mod_usertrack.la -rpath /usr/local/lib mod_usertrack.lo  
#libtool: link: gcc -fPIC -shared  -fPIC -DPIC  .libs/mod_usertrack.o    -O2   -Wl,-soname -Wl,mod_usertrack.so -o .libs/mod_usertrack.so
cd ".libs" && rm -f "mod_usertrack.la" && ln -s "../mod_usertrack.la" "mod_usertrack.la" && cd ..
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_proxy.lo -MD -MP -MF .deps/mod_proxy.Tpo -c -o mod_proxy.lo mod_proxy.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_proxy.lo -MD -MP -MF .deps/mod_proxy.Tpo -c mod_proxy.c  -fPIC -DPIC -o .libs/mod_proxy.o
mv -f .deps/mod_proxy.Tpo .deps/mod_proxy.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fPIC  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -module -export-dynamic -avoid-version  -o mod_proxy.la -rpath /usr/local/lib mod_proxy.lo  
#libtool: link: gcc -fPIC -shared  -fPIC -DPIC  .libs/mod_proxy.o    -O2   -Wl,-soname -Wl,mod_proxy.so -o .libs/mod_proxy.so
cd ".libs" && rm -f "mod_proxy.la" && ln -s "../mod_proxy.la" "mod_proxy.la" && cd ..
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_ssi_exprparser.lo -MD -MP -MF .deps/mod_ssi_exprparser.Tpo -c -o mod_ssi_exprparser.lo mod_ssi_exprparser.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_ssi_exprparser.lo -MD -MP -MF .deps/mod_ssi_exprparser.Tpo -c mod_ssi_exprparser.c  -fPIC -DPIC -o .libs/mod_ssi_exprparser.o
mv -f .deps/mod_ssi_exprparser.Tpo .deps/mod_ssi_exprparser.Plo
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_ssi_expr.lo -MD -MP -MF .deps/mod_ssi_expr.Tpo -c -o mod_ssi_expr.lo mod_ssi_expr.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_ssi_expr.lo -MD -MP -MF .deps/mod_ssi_expr.Tpo -c mod_ssi_expr.c  -fPIC -DPIC -o .libs/mod_ssi_expr.o
mv -f .deps/mod_ssi_expr.Tpo .deps/mod_ssi_expr.Plo
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_ssi.lo -MD -MP -MF .deps/mod_ssi.Tpo -c -o mod_ssi.lo mod_ssi.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_ssi.lo -MD -MP -MF .deps/mod_ssi.Tpo -c mod_ssi.c  -fPIC -DPIC -o .libs/mod_ssi.o
mv -f .deps/mod_ssi.Tpo .deps/mod_ssi.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fPIC  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -module -export-dynamic -avoid-version  -o mod_ssi.la -rpath /usr/local/lib mod_ssi_exprparser.lo mod_ssi_expr.lo mod_ssi.lo  -lpcre 
#libtool: link: gcc -fPIC -shared  -fPIC -DPIC  .libs/mod_ssi_exprparser.o .libs/mod_ssi_expr.o .libs/mod_ssi.o   -lpcre  -O2   -Wl,-soname -Wl,mod_ssi.so -o .libs/mod_ssi.so
cd ".libs" && rm -f "mod_ssi.la" && ln -s "../mod_ssi.la" "mod_ssi.la" && cd ..
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_secure_download.lo -MD -MP -MF .deps/mod_secure_download.Tpo -c -o mod_secure_download.lo mod_secure_download.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_secure_download.lo -MD -MP -MF .deps/mod_secure_download.Tpo -c mod_secure_download.c  -fPIC -DPIC -o .libs/mod_secure_download.o
mv -f .deps/mod_secure_download.Tpo .deps/mod_secure_download.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fPIC  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -module -export-dynamic -avoid-version  -o mod_secdownload.la -rpath /usr/local/lib mod_secure_download.lo  
#libtool: link: gcc -fPIC -shared  -fPIC -DPIC  .libs/mod_secure_download.o    -O2   -Wl,-soname -Wl,mod_secdownload.so -o .libs/mod_secdownload.so
cd ".libs" && rm -f "mod_secdownload.la" && ln -s "../mod_secdownload.la" "mod_secdownload.la" && cd ..
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_expire.lo -MD -MP -MF .deps/mod_expire.Tpo -c -o mod_expire.lo mod_expire.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_expire.lo -MD -MP -MF .deps/mod_expire.Tpo -c mod_expire.c  -fPIC -DPIC -o .libs/mod_expire.o
mv -f .deps/mod_expire.Tpo .deps/mod_expire.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fPIC  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -module -export-dynamic -avoid-version  -o mod_expire.la -rpath /usr/local/lib mod_expire.lo  
#libtool: link: gcc -fPIC -shared  -fPIC -DPIC  .libs/mod_expire.o    -O2   -Wl,-soname -Wl,mod_expire.so -o .libs/mod_expire.so
cd ".libs" && rm -f "mod_expire.la" && ln -s "../mod_expire.la" "mod_expire.la" && cd ..
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_evhost.lo -MD -MP -MF .deps/mod_evhost.Tpo -c -o mod_evhost.lo mod_evhost.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_evhost.lo -MD -MP -MF .deps/mod_evhost.Tpo -c mod_evhost.c  -fPIC -DPIC -o .libs/mod_evhost.o
mv -f .deps/mod_evhost.Tpo .deps/mod_evhost.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fPIC  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -module -export-dynamic -avoid-version  -o mod_evhost.la -rpath /usr/local/lib mod_evhost.lo  
#libtool: link: gcc -fPIC -shared  -fPIC -DPIC  .libs/mod_evhost.o    -O2   -Wl,-soname -Wl,mod_evhost.so -o .libs/mod_evhost.so
cd ".libs" && rm -f "mod_evhost.la" && ln -s "../mod_evhost.la" "mod_evhost.la" && cd ..
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_simple_vhost.lo -MD -MP -MF .deps/mod_simple_vhost.Tpo -c -o mod_simple_vhost.lo mod_simple_vhost.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_simple_vhost.lo -MD -MP -MF .deps/mod_simple_vhost.Tpo -c mod_simple_vhost.c  -fPIC -DPIC -o .libs/mod_simple_vhost.o
mv -f .deps/mod_simple_vhost.Tpo .deps/mod_simple_vhost.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fPIC  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -module -export-dynamic -avoid-version  -o mod_simple_vhost.la -rpath /usr/local/lib mod_simple_vhost.lo  
#libtool: link: gcc -fPIC -shared  -fPIC -DPIC  .libs/mod_simple_vhost.o    -O2   -Wl,-soname -Wl,mod_simple_vhost.so -o .libs/mod_simple_vhost.so
cd ".libs" && rm -f "mod_simple_vhost.la" && ln -s "../mod_simple_vhost.la" "mod_simple_vhost.la" && cd ..
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_fastcgi.lo -MD -MP -MF .deps/mod_fastcgi.Tpo -c -o mod_fastcgi.lo mod_fastcgi.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_fastcgi.lo -MD -MP -MF .deps/mod_fastcgi.Tpo -c mod_fastcgi.c  -fPIC -DPIC -o .libs/mod_fastcgi.o
mv -f .deps/mod_fastcgi.Tpo .deps/mod_fastcgi.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fPIC  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -module -export-dynamic -avoid-version  -o mod_fastcgi.la -rpath /usr/local/lib mod_fastcgi.lo  
#libtool: link: gcc -fPIC -shared  -fPIC -DPIC  .libs/mod_fastcgi.o    -O2   -Wl,-soname -Wl,mod_fastcgi.so -o .libs/mod_fastcgi.so
cd ".libs" && rm -f "mod_fastcgi.la" && ln -s "../mod_fastcgi.la" "mod_fastcgi.la" && cd ..
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_extforward.lo -MD -MP -MF .deps/mod_extforward.Tpo -c -o mod_extforward.lo mod_extforward.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_extforward.lo -MD -MP -MF .deps/mod_extforward.Tpo -c mod_extforward.c  -fPIC -DPIC -o .libs/mod_extforward.o
mv -f .deps/mod_extforward.Tpo .deps/mod_extforward.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fPIC  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -module -export-dynamic -avoid-version  -o mod_extforward.la -rpath /usr/local/lib mod_extforward.lo  
#libtool: link: gcc -fPIC -shared  -fPIC -DPIC  .libs/mod_extforward.o    -O2   -Wl,-soname -Wl,mod_extforward.so -o .libs/mod_extforward.so
cd ".libs" && rm -f "mod_extforward.la" && ln -s "../mod_extforward.la" "mod_extforward.la" && cd ..
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_access.lo -MD -MP -MF .deps/mod_access.Tpo -c -o mod_access.lo mod_access.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_access.lo -MD -MP -MF .deps/mod_access.Tpo -c mod_access.c  -fPIC -DPIC -o .libs/mod_access.o
mv -f .deps/mod_access.Tpo .deps/mod_access.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fPIC  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -module -export-dynamic -avoid-version  -o mod_access.la -rpath /usr/local/lib mod_access.lo  
#libtool: link: gcc -fPIC -shared  -fPIC -DPIC  .libs/mod_access.o    -O2   -Wl,-soname -Wl,mod_access.so -o .libs/mod_access.so
cd ".libs" && rm -f "mod_access.la" && ln -s "../mod_access.la" "mod_access.la" && cd ..
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_compress.lo -MD -MP -MF .deps/mod_compress.Tpo -c -o mod_compress.lo mod_compress.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_compress.lo -MD -MP -MF .deps/mod_compress.Tpo -c mod_compress.c  -fPIC -DPIC -o .libs/mod_compress.o
mv -f .deps/mod_compress.Tpo .deps/mod_compress.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fPIC  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -module -export-dynamic -avoid-version  -o mod_compress.la -rpath /usr/local/lib mod_compress.lo -lz -lbz2  
#libtool: link: gcc -fPIC -shared  -fPIC -DPIC  .libs/mod_compress.o   -lz -lbz2  -O2   -Wl,-soname -Wl,mod_compress.so -o .libs/mod_compress.so
cd ".libs" && rm -f "mod_compress.la" && ln -s "../mod_compress.la" "mod_compress.la" && cd ..
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_auth.lo -MD -MP -MF .deps/mod_auth.Tpo -c -o mod_auth.lo mod_auth.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_auth.lo -MD -MP -MF .deps/mod_auth.Tpo -c mod_auth.c  -fPIC -DPIC -o .libs/mod_auth.o
mv -f .deps/mod_auth.Tpo .deps/mod_auth.Plo
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT http_auth.lo -MD -MP -MF .deps/http_auth.Tpo -c -o http_auth.lo http_auth.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT http_auth.lo -MD -MP -MF .deps/http_auth.Tpo -c http_auth.c  -fPIC -DPIC -o .libs/http_auth.o
mv -f .deps/http_auth.Tpo .deps/http_auth.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fPIC  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -module -export-dynamic -avoid-version  -o mod_auth.la -rpath /usr/local/lib mod_auth.lo http_auth.lo -lcrypt     
#libtool: link: gcc -fPIC -shared  -fPIC -DPIC  .libs/mod_auth.o .libs/http_auth.o   -lcrypt  -O2   -Wl,-soname -Wl,mod_auth.so -o .libs/mod_auth.so
cd ".libs" && rm -f "mod_auth.la" && ln -s "../mod_auth.la" "mod_auth.la" && cd ..
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_rewrite.lo -MD -MP -MF .deps/mod_rewrite.Tpo -c -o mod_rewrite.lo mod_rewrite.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_rewrite.lo -MD -MP -MF .deps/mod_rewrite.Tpo -c mod_rewrite.c  -fPIC -DPIC -o .libs/mod_rewrite.o
mv -f .deps/mod_rewrite.Tpo .deps/mod_rewrite.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fPIC  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -module -export-dynamic -avoid-version  -o mod_rewrite.la -rpath /usr/local/lib mod_rewrite.lo -lpcre  
#libtool: link: gcc -fPIC -shared  -fPIC -DPIC  .libs/mod_rewrite.o   -lpcre  -O2   -Wl,-soname -Wl,mod_rewrite.so -o .libs/mod_rewrite.so
cd ".libs" && rm -f "mod_rewrite.la" && ln -s "../mod_rewrite.la" "mod_rewrite.la" && cd ..
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_redirect.lo -MD -MP -MF .deps/mod_redirect.Tpo -c -o mod_redirect.lo mod_redirect.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_redirect.lo -MD -MP -MF .deps/mod_redirect.Tpo -c mod_redirect.c  -fPIC -DPIC -o .libs/mod_redirect.o
mv -f .deps/mod_redirect.Tpo .deps/mod_redirect.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fPIC  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -module -export-dynamic -avoid-version  -o mod_redirect.la -rpath /usr/local/lib mod_redirect.lo -lpcre  
#libtool: link: gcc -fPIC -shared  -fPIC -DPIC  .libs/mod_redirect.o   -lpcre  -O2   -Wl,-soname -Wl,mod_redirect.so -o .libs/mod_redirect.so
cd ".libs" && rm -f "mod_redirect.la" && ln -s "../mod_redirect.la" "mod_redirect.la" && cd ..
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_status.lo -MD -MP -MF .deps/mod_status.Tpo -c -o mod_status.lo mod_status.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_status.lo -MD -MP -MF .deps/mod_status.Tpo -c mod_status.c  -fPIC -DPIC -o .libs/mod_status.o
mv -f .deps/mod_status.Tpo .deps/mod_status.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fPIC  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -module -export-dynamic -avoid-version  -o mod_status.la -rpath /usr/local/lib mod_status.lo  
#libtool: link: gcc -fPIC -shared  -fPIC -DPIC  .libs/mod_status.o    -O2   -Wl,-soname -Wl,mod_status.so -o .libs/mod_status.so
cd ".libs" && rm -f "mod_status.la" && ln -s "../mod_status.la" "mod_status.la" && cd ..
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_accesslog.lo -MD -MP -MF .deps/mod_accesslog.Tpo -c -o mod_accesslog.lo mod_accesslog.c
#libtool: compile:  gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR=\"/usr/local/lib\" -DSBIN_DIR=\"/usr/local/sbin\" -I. -I.. -D_REENTRANT -D__EXTENSIONS__ -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT mod_accesslog.lo -MD -MP -MF .deps/mod_accesslog.Tpo -c mod_accesslog.c  -fPIC -DPIC -o .libs/mod_accesslog.o
mv -f .deps/mod_accesslog.Tpo .deps/mod_accesslog.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fPIC  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -module -export-dynamic -avoid-version  -o mod_accesslog.la -rpath /usr/local/lib mod_accesslog.lo  
#libtool: link: gcc -fPIC -shared  -fPIC -DPIC  .libs/mod_accesslog.o    -O2   -Wl,-soname -Wl,mod_accesslog.so -o .libs/mod_accesslog.so
cd ".libs" && rm -f "mod_accesslog.la" && ln -s "../mod_accesslog.la" "mod_accesslog.la" && cd ..
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..  -DDEBUG_PROC_OPEN -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT proc_open-proc_open.o -MD -MP -MF .deps/proc_open-proc_open.Tpo -c -o proc_open-proc_open.o `test -f 'proc_open.c' || echo './'`proc_open.c
mv -f .deps/proc_open-proc_open.Tpo .deps/proc_open-proc_open.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..  -DDEBUG_PROC_OPEN -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT proc_open-buffer.o -MD -MP -MF .deps/proc_open-buffer.Tpo -c -o proc_open-buffer.o `test -f 'buffer.c' || echo './'`buffer.c
mv -f .deps/proc_open-buffer.Tpo .deps/proc_open-buffer.Po
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fPIC  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99   -o proc_open proc_open-proc_open.o proc_open-buffer.o  
#libtool: link: gcc -fPIC -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -o proc_open proc_open-proc_open.o proc_open-buffer.o 
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT server.o -MD -MP -MF .deps/server.Tpo -c -o server.o server.c
mv -f .deps/server.Tpo .deps/server.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT response.o -MD -MP -MF .deps/response.Tpo -c -o response.o response.c
mv -f .deps/response.Tpo .deps/response.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT connections.o -MD -MP -MF .deps/connections.Tpo -c -o connections.o connections.c
mv -f .deps/connections.Tpo .deps/connections.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT network.o -MD -MP -MF .deps/network.Tpo -c -o network.o network.c
mv -f .deps/network.Tpo .deps/network.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT configfile.o -MD -MP -MF .deps/configfile.Tpo -c -o configfile.o configfile.c
mv -f .deps/configfile.Tpo .deps/configfile.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT configparser.o -MD -MP -MF .deps/configparser.Tpo -c -o configparser.o configparser.c
mv -f .deps/configparser.Tpo .deps/configparser.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT request.o -MD -MP -MF .deps/request.Tpo -c -o request.o request.c
mv -f .deps/request.Tpo .deps/request.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT proc_open.o -MD -MP -MF .deps/proc_open.Tpo -c -o proc_open.o proc_open.c
mv -f .deps/proc_open.Tpo .deps/proc_open.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT buffer.o -MD -MP -MF .deps/buffer.Tpo -c -o buffer.o buffer.c
mv -f .deps/buffer.Tpo .deps/buffer.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT log.o -MD -MP -MF .deps/log.Tpo -c -o log.o log.c
mv -f .deps/log.Tpo .deps/log.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT keyvalue.o -MD -MP -MF .deps/keyvalue.Tpo -c -o keyvalue.o keyvalue.c
mv -f .deps/keyvalue.Tpo .deps/keyvalue.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT chunk.o -MD -MP -MF .deps/chunk.Tpo -c -o chunk.o chunk.c
mv -f .deps/chunk.Tpo .deps/chunk.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT http_chunk.o -MD -MP -MF .deps/http_chunk.Tpo -c -o http_chunk.o http_chunk.c
mv -f .deps/http_chunk.Tpo .deps/http_chunk.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT stream.o -MD -MP -MF .deps/stream.Tpo -c -o stream.o stream.c
mv -f .deps/stream.Tpo .deps/stream.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT fdevent.o -MD -MP -MF .deps/fdevent.Tpo -c -o fdevent.o fdevent.c
mv -f .deps/fdevent.Tpo .deps/fdevent.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT stat_cache.o -MD -MP -MF .deps/stat_cache.Tpo -c -o stat_cache.o stat_cache.c
mv -f .deps/stat_cache.Tpo .deps/stat_cache.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT plugin.o -MD -MP -MF .deps/plugin.Tpo -c -o plugin.o plugin.c
mv -f .deps/plugin.Tpo .deps/plugin.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT joblist.o -MD -MP -MF .deps/joblist.Tpo -c -o joblist.o joblist.c
mv -f .deps/joblist.Tpo .deps/joblist.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT etag.o -MD -MP -MF .deps/etag.Tpo -c -o etag.o etag.c
mv -f .deps/etag.Tpo .deps/etag.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT array.o -MD -MP -MF .deps/array.Tpo -c -o array.o array.c
mv -f .deps/array.Tpo .deps/array.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT data_string.o -MD -MP -MF .deps/data_string.Tpo -c -o data_string.o data_string.c
mv -f .deps/data_string.Tpo .deps/data_string.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT data_count.o -MD -MP -MF .deps/data_count.Tpo -c -o data_count.o data_count.c
mv -f .deps/data_count.Tpo .deps/data_count.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT data_array.o -MD -MP -MF .deps/data_array.Tpo -c -o data_array.o data_array.c
mv -f .deps/data_array.Tpo .deps/data_array.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT data_integer.o -MD -MP -MF .deps/data_integer.Tpo -c -o data_integer.o data_integer.c
mv -f .deps/data_integer.Tpo .deps/data_integer.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT md5.o -MD -MP -MF .deps/md5.Tpo -c -o md5.o md5.c
mv -f .deps/md5.Tpo .deps/md5.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT data_fastcgi.o -MD -MP -MF .deps/data_fastcgi.Tpo -c -o data_fastcgi.o data_fastcgi.c
mv -f .deps/data_fastcgi.Tpo .deps/data_fastcgi.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT fdevent_select.o -MD -MP -MF .deps/fdevent_select.Tpo -c -o fdevent_select.o fdevent_select.c
mv -f .deps/fdevent_select.Tpo .deps/fdevent_select.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT fdevent_libev.o -MD -MP -MF .deps/fdevent_libev.Tpo -c -o fdevent_libev.o fdevent_libev.c
mv -f .deps/fdevent_libev.Tpo .deps/fdevent_libev.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT fdevent_poll.o -MD -MP -MF .deps/fdevent_poll.Tpo -c -o fdevent_poll.o fdevent_poll.c
mv -f .deps/fdevent_poll.Tpo .deps/fdevent_poll.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT fdevent_linux_sysepoll.o -MD -MP -MF .deps/fdevent_linux_sysepoll.Tpo -c -o fdevent_linux_sysepoll.o fdevent_linux_sysepoll.c
mv -f .deps/fdevent_linux_sysepoll.Tpo .deps/fdevent_linux_sysepoll.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT fdevent_solaris_devpoll.o -MD -MP -MF .deps/fdevent_solaris_devpoll.Tpo -c -o fdevent_solaris_devpoll.o fdevent_solaris_devpoll.c
mv -f .deps/fdevent_solaris_devpoll.Tpo .deps/fdevent_solaris_devpoll.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT fdevent_solaris_port.o -MD -MP -MF .deps/fdevent_solaris_port.Tpo -c -o fdevent_solaris_port.o fdevent_solaris_port.c
mv -f .deps/fdevent_solaris_port.Tpo .deps/fdevent_solaris_port.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT fdevent_freebsd_kqueue.o -MD -MP -MF .deps/fdevent_freebsd_kqueue.Tpo -c -o fdevent_freebsd_kqueue.o fdevent_freebsd_kqueue.c
mv -f .deps/fdevent_freebsd_kqueue.Tpo .deps/fdevent_freebsd_kqueue.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT data_config.o -MD -MP -MF .deps/data_config.Tpo -c -o data_config.o data_config.c
mv -f .deps/data_config.Tpo .deps/data_config.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT bitset.o -MD -MP -MF .deps/bitset.Tpo -c -o bitset.o bitset.c
mv -f .deps/bitset.Tpo .deps/bitset.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT inet_ntop_cache.o -MD -MP -MF .deps/inet_ntop_cache.Tpo -c -o inet_ntop_cache.o inet_ntop_cache.c
mv -f .deps/inet_ntop_cache.Tpo .deps/inet_ntop_cache.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT crc32.o -MD -MP -MF .deps/crc32.Tpo -c -o crc32.o crc32.c
mv -f .deps/crc32.Tpo .deps/crc32.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT connections-glue.o -MD -MP -MF .deps/connections-glue.Tpo -c -o connections-glue.o connections-glue.c
mv -f .deps/connections-glue.Tpo .deps/connections-glue.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT configfile-glue.o -MD -MP -MF .deps/configfile-glue.Tpo -c -o configfile-glue.o configfile-glue.c
mv -f .deps/configfile-glue.Tpo .deps/configfile-glue.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT http-header-glue.o -MD -MP -MF .deps/http-header-glue.Tpo -c -o http-header-glue.o http-header-glue.c
mv -f .deps/http-header-glue.Tpo .deps/http-header-glue.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT network_write.o -MD -MP -MF .deps/network_write.Tpo -c -o network_write.o network_write.c
mv -f .deps/network_write.Tpo .deps/network_write.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT network_linux_sendfile.o -MD -MP -MF .deps/network_linux_sendfile.Tpo -c -o network_linux_sendfile.o network_linux_sendfile.c
mv -f .deps/network_linux_sendfile.Tpo .deps/network_linux_sendfile.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT network_freebsd_sendfile.o -MD -MP -MF .deps/network_freebsd_sendfile.Tpo -c -o network_freebsd_sendfile.o network_freebsd_sendfile.c
mv -f .deps/network_freebsd_sendfile.Tpo .deps/network_freebsd_sendfile.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT network_writev.o -MD -MP -MF .deps/network_writev.Tpo -c -o network_writev.o network_writev.c
mv -f .deps/network_writev.Tpo .deps/network_writev.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT network_solaris_sendfilev.o -MD -MP -MF .deps/network_solaris_sendfilev.Tpo -c -o network_solaris_sendfilev.o network_solaris_sendfilev.c
mv -f .deps/network_solaris_sendfilev.Tpo .deps/network_solaris_sendfilev.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT network_openssl.o -MD -MP -MF .deps/network_openssl.Tpo -c -o network_openssl.o network_openssl.c
mv -f .deps/network_openssl.Tpo .deps/network_openssl.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT splaytree.o -MD -MP -MF .deps/splaytree.Tpo -c -o splaytree.o splaytree.c
mv -f .deps/splaytree.Tpo .deps/splaytree.Po
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT status_counter.o -MD -MP -MF .deps/status_counter.Tpo -c -o status_counter.o status_counter.c
mv -f .deps/status_counter.Tpo .deps/status_counter.Po
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fPIC  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -export-dynamic -shared -fPIC  -o lighttpd server.o response.o connections.o network.o configfile.o configparser.o request.o proc_open.o buffer.o log.o keyvalue.o chunk.o http_chunk.o stream.o fdevent.o stat_cache.o plugin.o joblist.o etag.o array.o data_string.o data_count.o data_array.o data_integer.o md5.o data_fastcgi.o fdevent_select.o fdevent_libev.o fdevent_poll.o fdevent_linux_sysepoll.o fdevent_solaris_devpoll.o fdevent_solaris_port.o fdevent_freebsd_kqueue.o data_config.o bitset.o inet_ntop_cache.o crc32.o connections-glue.o configfile-glue.o http-header-glue.o network_write.o network_linux_sendfile.o network_freebsd_sendfile.o network_writev.o network_solaris_sendfilev.o network_openssl.o splaytree.o status_counter.o -lpcre -ldl       
#libtool: link: gcc -fPIC -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -o lighttpd server.o response.o connections.o network.o configfile.o configparser.o request.o proc_open.o buffer.o log.o keyvalue.o chunk.o http_chunk.o stream.o fdevent.o stat_cache.o plugin.o joblist.o etag.o array.o data_string.o data_count.o data_array.o data_integer.o md5.o data_fastcgi.o fdevent_select.o fdevent_libev.o fdevent_poll.o fdevent_linux_sysepoll.o fdevent_solaris_devpoll.o fdevent_solaris_port.o fdevent_freebsd_kqueue.o data_config.o bitset.o inet_ntop_cache.o crc32.o connections-glue.o configfile-glue.o http-header-glue.o network_write.o network_linux_sendfile.o network_freebsd_sendfile.o network_writev.o network_solaris_sendfilev.o network_openssl.o splaytree.o status_counter.o -Wl,--export-dynamic  -lpcre -ldl
gcc -fPIC -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -shared -fPIC -o lighttpd2 server.o response.o connections.o network.o configfile.o configparser.o request.o proc_open.o buffer.o log.o keyvalue.o chunk.o http_chunk.o stream.o fdevent.o stat_cache.o plugin.o joblist.o etag.o array.o data_string.o data_count.o data_array.o data_integer.o md5.o data_fastcgi.o fdevent_select.o fdevent_libev.o fdevent_poll.o fdevent_linux_sysepoll.o fdevent_solaris_devpoll.o fdevent_solaris_port.o fdevent_freebsd_kqueue.o data_config.o bitset.o inet_ntop_cache.o crc32.o connections-glue.o configfile-glue.o http-header-glue.o network_write.o network_linux_sendfile.o network_freebsd_sendfile.o network_writev.o network_solaris_sendfilev.o network_openssl.o splaytree.o status_counter.o -Wl,--export-dynamic  -lpcre -ldl
gcc -fPIC -DHAVE_CONFIG_H  -DLIBRARY_DIR="\"/usr/local/lib\"" -DSBIN_DIR="\"/usr/local/sbin\"" -I. -I..   -D_REENTRANT -D__EXTENSIONS__  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -MT lighttpd-angel.o -MD -MP -MF .deps/lighttpd-angel.Tpo -c -o lighttpd-angel.o lighttpd-angel.c
mv -f .deps/lighttpd-angel.Tpo .deps/lighttpd-angel.Po
/bin/sh ../libtool  --tag=CC   --mode=link gcc -fPIC  -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99   -o lighttpd-angel lighttpd-angel.o  
#libtool: link: gcc -fPIC -g -O2 -Wall -W -Wshadow -pedantic -std=gnu99 -o lighttpd-angel lighttpd-angel.o 

